// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempusCare.Api.Infrastructure.Data;

#nullable disable

namespace TempusCare.Api.Infrastructure.Migrations
{
    [DbContext(typeof(TempusCareDbContext))]
    partial class TempusCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AdministradorConsultorio", b =>
                {
                    b.Property<string>("Cuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultorioCuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cuil");

                    b.HasIndex("ConsultorioCuit");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("AdministradoresConsultorio");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AdministradorInstitucion", b =>
                {
                    b.Property<string>("Cuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cuil");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("AdministradoresInstitucion");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsultorioCuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfesionalCuil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultorioCuit");

                    b.HasIndex("ProfesionalCuil");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Asistente", b =>
                {
                    b.Property<string>("Cuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminConsultorioCuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultorioCuit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cuil");

                    b.HasIndex("AdminConsultorioCuil");

                    b.HasIndex("ConsultorioCuit");

                    b.HasIndex("DireccionId");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Asistentes");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AsistenteAgenda", b =>
                {
                    b.Property<string>("AsistenteCuil")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AsistenteCuil", "AgendaId");

                    b.HasIndex("AgendaId");

                    b.ToTable("AsistenteAgendas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cobertura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentoPedidoMedico")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstudioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteCuil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EstudioId");

                    b.HasIndex("PacienteCuil");

                    b.HasIndex("TurnoId")
                        .IsUnique()
                        .HasFilter("\"Estado\" != 5");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfesionalEstudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.HasIndex("ProfesionalEstudioId", "ObraSocialId")
                        .IsUnique();

                    b.ToTable("Coberturas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Consultorio", b =>
                {
                    b.Property<string>("Cuit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("NivelAccesibilidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cuit");

                    b.HasIndex("DireccionId");

                    b.HasIndex("InstitucionId");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cuestionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atencion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CitaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<int>("Profesionalismo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puntualidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Depto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Estudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EspecialidadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoContacto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discapacidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnfermedadesCronicas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupSang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medicamentos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteCuil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteCuil")
                        .IsUnique();

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Institucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catalogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CitaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HistoriaClinicaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfesionalCuil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("ProfesionalCuil");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Paciente", b =>
                {
                    b.Property<string>("Cuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cuil");

                    b.HasIndex("DireccionId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.PacienteObraSocial", b =>
                {
                    b.Property<string>("PacienteCuil")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PacienteCuil", "ObraSocialId");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("PacienteObrasSociales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Profesional", b =>
                {
                    b.Property<string>("Cuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cuil");

                    b.HasIndex("DireccionId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalConsultorio", b =>
                {
                    b.Property<string>("ProfesionalCuil")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultorioCuit")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfesionalCuil", "ConsultorioCuit");

                    b.HasIndex("ConsultorioCuit");

                    b.ToTable("ProfesionalConsultorios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalEspecialidad", b =>
                {
                    b.Property<string>("ProfesionalCuil")
                        .HasColumnType("TEXT");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfesionalCuil", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("ProfesionalEspecialidades");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracionTurno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioParticular")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfesionalCuil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstudioId");

                    b.HasIndex("ProfesionalCuil", "EstudioId")
                        .IsUnique();

                    b.ToTable("ProfesionalEstudios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalObraSocial", b =>
                {
                    b.Property<string>("ProfesionalCuil")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfesionalCuil", "ObraSocialId");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("ProfesionalObrasSociales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgendaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CitaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.HasIndex("CitaId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AdministradorConsultorio", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Consultorio", "Consultorio")
                        .WithMany("Administradores")
                        .HasForeignKey("ConsultorioCuit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("AdministradorConsultorio")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.AdministradorConsultorio", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AdministradorInstitucion", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Institucion", "Institucion")
                        .WithMany("Administradores")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("AdministradorInstitucion")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.AdministradorInstitucion", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Agenda", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Consultorio", "Consultorio")
                        .WithMany("Agendas")
                        .HasForeignKey("ConsultorioCuit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Agendas")
                        .HasForeignKey("ProfesionalCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Asistente", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.AdministradorConsultorio", "AdminConsultorio")
                        .WithMany("Asistentes")
                        .HasForeignKey("AdminConsultorioCuil")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Consultorio", "Consultorio")
                        .WithMany("Asistentes")
                        .HasForeignKey("ConsultorioCuit")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Institucion", "Institucion")
                        .WithMany("Asistentes")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Asistente")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.Asistente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminConsultorio");

                    b.Navigation("Consultorio");

                    b.Navigation("Direccion");

                    b.Navigation("Institucion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AsistenteAgenda", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Agenda", "Agenda")
                        .WithMany("AsistentesAsignados")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Asistente", "Asistente")
                        .WithMany("AgendasAsignadas")
                        .HasForeignKey("AsistenteCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Asistente");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cita", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Estudio", "Estudio")
                        .WithMany()
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudio");

                    b.Navigation("Paciente");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cobertura", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany("Coberturas")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.ProfesionalEstudio", "ProfesionalEstudio")
                        .WithMany("Coberturas")
                        .HasForeignKey("ProfesionalEstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");

                    b.Navigation("ProfesionalEstudio");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Consultorio", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Institucion", "Institucion")
                        .WithMany("Consultorios")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Direccion");

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cuestionario", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Cita", "Cita")
                        .WithOne("Cuestionario")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.Cuestionario", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Estudio", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("Estudios")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.HistoriaClinica", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.HistoriaClinica", "PacienteCuil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Institucion", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Institucion")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.Institucion", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Observacion", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Cita", "Cita")
                        .WithOne("Observacion")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.Observacion", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TempusCare.Api.Domain.Entities.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Observaciones")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TempusCare.Api.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Observaciones")
                        .HasForeignKey("ProfesionalCuil")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cita");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.Paciente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.PacienteObraSocial", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany("Pacientes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Paciente", "Paciente")
                        .WithMany("ObrasSociales")
                        .HasForeignKey("PacienteCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Profesional", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TempusCare.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("TempusCare.Api.Domain.Entities.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalConsultorio", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Consultorio", "Consultorio")
                        .WithMany("Profesionales")
                        .HasForeignKey("ConsultorioCuit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Consultorios")
                        .HasForeignKey("ProfesionalCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalEspecialidad", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("Profesionales")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfesionalCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalEstudio", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Estudio", "Estudio")
                        .WithMany("ProfesionalEstudios")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Estudios")
                        .HasForeignKey("ProfesionalCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudio");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalObraSocial", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany("Profesionales")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Profesional", "Profesional")
                        .WithMany("ObrasSociales")
                        .HasForeignKey("ProfesionalCuil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Turno", b =>
                {
                    b.HasOne("TempusCare.Api.Domain.Entities.Agenda", "Agenda")
                        .WithMany("Turnos")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempusCare.Api.Domain.Entities.Cita", "Cita")
                        .WithMany("Turnos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agenda");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.AdministradorConsultorio", b =>
                {
                    b.Navigation("Asistentes");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Agenda", b =>
                {
                    b.Navigation("AsistentesAsignados");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Asistente", b =>
                {
                    b.Navigation("AgendasAsignadas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Cita", b =>
                {
                    b.Navigation("Cuestionario");

                    b.Navigation("Observacion");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Consultorio", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Agendas");

                    b.Navigation("Asistentes");

                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Especialidad", b =>
                {
                    b.Navigation("Estudios");

                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Estudio", b =>
                {
                    b.Navigation("ProfesionalEstudios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.HistoriaClinica", b =>
                {
                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Institucion", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Asistentes");

                    b.Navigation("Consultorios");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ObraSocial", b =>
                {
                    b.Navigation("Coberturas");

                    b.Navigation("Pacientes");

                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("ObrasSociales");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Profesional", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Consultorios");

                    b.Navigation("Especialidades");

                    b.Navigation("Estudios");

                    b.Navigation("ObrasSociales");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.ProfesionalEstudio", b =>
                {
                    b.Navigation("Coberturas");
                });

            modelBuilder.Entity("TempusCare.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AdministradorConsultorio");

                    b.Navigation("AdministradorInstitucion");

                    b.Navigation("Asistente");

                    b.Navigation("Institucion");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });
#pragma warning restore 612, 618
        }
    }
}
